# using this awsome prebuild
FROM 123majumundur/php-7.1-nginx:cicd


#install prestisimo for faster deps installation 
RUN composer global require hirak/prestissimo

#make directroy for hosting the apps
RUN mkdir /home/app/app
WORKDIR /home/app/app

#install depedencis
COPY composer.json composer.json
RUN composer install prefer-dist --no-script --no-dev --no-autoloader && rm -rf /home/app/.composer

#copy codebase
COPY --chown=app:root . ./

#finishcomposer
#run composer dump-autoloaded
RUN composer dump-autoloaded --no-script --no-dev --optimize

EXPOSE 8080